name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            autoconf \
            automake \
            autopoint \
            gettext \
            libtool \
            libltdl-dev \
            pkg-config \
            build-essential \
            ccache \
            cmake \
            libffi-dev \
            libssl-dev \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libtinfo6

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --upgrade buildozer cython

      - name: Prepare Buildozer
        run: |
          sed -i 's/^# *android.accept_sdk_license = False/android.accept_sdk_license = True/' buildozer.spec || true

      - name: Build APK
        run: |
          yes | buildozer android clean
          yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Edy-P2P-Chat-APK
          path: bin/*.apk
